import { Oswald } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const oswald = Oswald({
  weight: ["700"],
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"

    >
      <body className={`min-h-full flex flex-col ${oswald.className}`}>

        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
