import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/shared/Navbar";

const oswald = Oswald({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-oswald",
});

const inter = Inter({
  weight: ["100"],
  subsets: ["latin"],
  variable: "--font-inter",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={`min-h-full flex flex-col ${oswald.variable} ${inter.variable}`}>

        <Navbar></Navbar>

        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
